<a href="https://colab.research.google.com/github/hayaboy/ADP_Practical_Exam/blob/main/SVD(Singular_Value_Decomposition%2C_%ED%8A%B9%EC%9D%B4%EA%B0%92_%EB%B6%84%ED%95%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 임의의 행렬 A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# SVD 수행
U, Sigma, VT = np.linalg.svd(A)

# U, Sigma, VT 출력
print("U:\n", U)
print("Sigma:\n", Sigma)
print("VT:\n", VT)

# 원본 행렬 복원
Sigma_full = np.zeros_like(A, dtype=float)
np.fill_diagonal(Sigma_full, Sigma)
#행렬 곱셈
A_reconstructed = U @ Sigma_full @ VT

print("Reconstructed A:\n", A_reconstructed)


U:
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Sigma:
 [1.68481034e+01 1.06836951e+00 4.41842475e-16]
VT:
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
Reconstructed A:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
